apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    name: auth
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: auth
          image: meeckey/kub-demo-auth:latest
          