apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    name: tasks
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tasks
  template:
    metadata:
      labels:
        name: tasks
    spec:
      containers:
        - name: task-image
          image: meeckey/kub-demo-tasks:latest
          env:
            - name: AUTH_URI
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks